version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docsrc/source/conf.py

python:
   install:
      - method: pip
        path: .
      - method: setuptools
        path: .
   version: 3.8
